"""Command-line tool to generate level JSON + assets.

Example usage:

    python -m backend.cli_generate --level 1 --num-rounds 5 \
        --out-json docs/levels/level-1.json \
        --assets-dir docs/assets
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import random

from .model import LevelSpec, RoundSpec, to_json_dict
from .rounds import build_round


def build_dummy_intro_slides() -> list[dict]:
  """Return a small list of intro slides as Python dicts.

  You can later move this to a dedicated config file or generate it programmatically.
  """

  return [
    {
      "title": "Welcome to Stabilizer Survival",
      "text": "Alice's logical qubit is encoded in a stabilizer code. Bob attacks via CZ and Pauli rotations.",
    },
    {
      "title": "Your task",
      "text": "In each round, choose a Pauli measurement that keeps the logical information safe.",
    },
  ]


def main() -> None:
  parser = argparse.ArgumentParser()
  parser.add_argument("--level", type=int, default=1, help="Level number (e.g. 1)")
  parser.add_argument("--num-rounds", type=int, default=3, help="Number of rounds to generate")
  parser.add_argument("--out-json", type=Path, default=Path("docs/levels/level-1.json"))
  parser.add_argument("--assets-dir", type=Path, default=Path("docs/assets"))
  parser.add_argument("--seed", type=int, default=42)

  args = parser.parse_args()

  rng = random.Random(args.seed)
  assets_dir = args.assets_dir
  assets_dir.mkdir(parents=True, exist_ok=True)

  rounds: list[RoundSpec] = []
  for i in range(args.num_rounds):
    round_spec = build_round(level=args.level, round_index=i, assets_dir=assets_dir)
    rounds.append(round_spec)

  level_spec = LevelSpec(
    id=f"level-{args.level}",
    title=f"Level {args.level} – Autogenerated",
    description="Level generated by backend.cli_generate.",
    round_time_limit_seconds=15,
    intro_slides=build_dummy_intro_slides(),
    rounds=rounds,
  )

  args.out_json.parent.mkdir(parents=True, exist_ok=True)
  with args.out_json.open("w", encoding="utf-8") as f:
    json.dump(to_json_dict(level_spec), f, indent=2)

  print(f"Wrote level JSON to {args.out_json}")
  print(f"Assets directory: {assets_dir}")


if __name__ == "__main__":  # pragma: no cover
  main()
